"use client";
import { useEffect,useMemo,useState } from "react";
type Product={rank:number;id:string;brand:string;name:string;price:string;url:string};
type Board={country:string;platform:string;category:string;status:"success"|"failed"|"pending";fetchedAt:string|null;lastSuccessAt:string|null;error:string|null;products:Product[]};
type Snapshot={date:string;generatedAt:string;boards:Board[]};
const countries=[{id:"AE",label:"阿联酋"},{id:"SA",label:"沙特"},{id:"EG",label:"埃及"}],platforms=[{id:"amazon",label:"Amazon"},{id:"noon",label:"Noon"}],categories=[{id:"phone",label:"手机"},{id:"audio",label:"音频"},{id:"wearable",label:"穿戴"},{id:"tablet",label:"平板"}];
const fmt=(v:string|null)=>v?new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Dubai",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(v)):"—";
export default function BestsellersPage(){
 const[country,setCountry]=useState("AE"),[platform,setPlatform]=useState("amazon"),[category,setCategory]=useState("phone"),[dates,setDates]=useState<string[]>([]),[current,setCurrent]=useState<Snapshot|null>(null),[compare,setCompare]=useState<Snapshot|null>(null),[compareMode,setCompareMode]=useState("7"),[customDate,setCustomDate]=useState(""),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
 useEffect(()=>{(async()=>{try{const index=await fetch("/data/bestsellers/index.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("数据索引不可用");return r.json()});const ds:string[]=index.dates||[];setDates(ds);if(!ds.length)throw Error("等待首次采集");setCurrent(await fetch(`/data/bestsellers/${ds[0]}.json`,{cache:"no-store"}).then(r=>r.json()));setCustomDate(ds[Math.min(6,ds.length-1)]||ds[0])}catch(e){setLoadError(e instanceof Error?e.message:"数据读取失败")}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(!current||!dates.length)return;const target=compareMode==="custom"?customDate:dates[Math.min(Number(compareMode)-1,dates.length-1)];if(!target||target===current.date){setCompare(null);return}fetch(`/data/bestsellers/${target}.json`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setCompare).catch(()=>setCompare(null))},[compareMode,customDate,current,dates]);
 const board=current?.boards.find(x=>x.country===country&&x.platform===platform&&x.category===category),oldBoard=compare?.boards.find(x=>x.country===country&&x.platform===platform&&x.category===category),oldRanks=useMemo(()=>new Map((oldBoard?.products||[]).map(x=>[x.id,x.rank])),[oldBoard]),successCount=current?.boards.filter(x=>x.status==="success").length||0,failedCount=current?.boards.filter(x=>x.status==="failed").length||0;
 return <main className="rank-page live-rank"><nav className="english-nav"><a className="brand" href="/"><span className="brand-dot">A</span><span>ALEX / CHANNEL RADAR</span></a><a className="back-home" href="/">← 返回工具中枢</a></nav><header className="rank-head"><div><small>DAILY E-COMMERCE BESTSELLER MONITOR</small><h1>电渠 TOP 畅销品<br/><em>监控看板</em></h1><p>3 个国家 × 2 个平台 × 4 个品类 · 每日自动采集</p></div><div className="rank-time"><span>最新数据（迪拜时间）</span><b>{current?.date||"等待采集"}</b><strong>{current?fmt(current.generatedAt):"—"}</strong><i className={failedCount?"status-warn":"status-live"}>{failedCount?`${failedCount} 个榜单失败`:loading?"读取中":"采集状态正常"}</i></div></header>
 <section className="rank-wrap"><div className={`integrity ${failedCount||loadError?"integrity-warn":""}`}><b>{loadError?"! 数据尚不可用":failedCount?"! 部分榜单抓取失败":"✓ 本次采集完成"}</b><span>{loadError||`${successCount}/24 成功 · ${failedCount}/24 失败。失败区域不会沿用旧数据冒充当日结果。`}</span></div>
 <div className="radar-controls"><Filter title="国家" items={countries} value={country} onChange={setCountry}/><Filter title="平台" items={platforms} value={platform} onChange={setPlatform}/><Filter title="品类" items={categories} value={category} onChange={setCategory}/><div className="control-group"><small>对比周期</small><div>{[{id:"7",label:"7天"},{id:"14",label:"14天"},{id:"30",label:"30天"},{id:"custom",label:"指定日期"}].map(x=><button key={x.id} className={compareMode===x.id?"active":""} onClick={()=>setCompareMode(x.id)}>{x.label}</button>)}</div>{compareMode==="custom"&&<select value={customDate} onChange={e=>setCustomDate(e.target.value)}>{dates.map(d=><option key={d}>{d}</option>)}</select>}</div></div>
 <div className="rank-kpis"><article><small>当前榜单</small><strong>{board?.products.length||0}<em>/20</em></strong><span>{countries.find(x=>x.id===country)?.label} · {platforms.find(x=>x.id===platform)?.label}</span></article><article><small>采集成功</small><strong>{successCount}<em>/24</em></strong><span>当日完整榜单</span></article><article><small>采集失败</small><strong className={failedCount?"negative":"positive"}>{failedCount}</strong><span>失败将明确展示</span></article><article><small>历史快照</small><strong>{dates.length}</strong><span>可选择具体日期</span></article></div>
 <div className="rank-section-title"><span>01</span><div><h2>{countries.find(x=>x.id===country)?.label} · {platforms.find(x=>x.id===platform)?.label} · {categories.find(x=>x.id===category)?.label}</h2><small>CURRENT RANKING & HISTORICAL MOVEMENT</small></div></div>
 {!board||board.status!=="success"?<Failure board={board} loading={loading}/>:<div className="rank-table"><div className="rank-tr rank-th"><span>排名</span><span>变化</span><span>品牌</span><span>产品</span><span>价格</span><span>来源</span></div>{board.products.map(x=>{const before=oldRanks.get(x.id),delta=before?before-x.rank:null;return <div className="rank-tr" key={x.id}><b>#{x.rank}</b><i className={delta&&delta>0?"positive":delta&&delta<0?"negative":""}>{before==null?(compare?"NEW":"—"):delta===0?"—":delta>0?`↑ ${delta}`:`↓ ${Math.abs(delta)}`}</i><strong>{x.brand||"—"}</strong><span>{x.name}</span><span>{x.price||"—"}</span><a href={x.url} target="_blank" rel="noreferrer">查看 ↗</a></div>})}</div>}
 <div className="source-note"><b>数据口径</b><p>按各平台公开搜索/畅销排序页面采集，排名代表抓取时页面展示顺序，不等同于平台官方销量。网页结构、验证码或访问限制都可能导致失败；失败时显示原因和上次成功时间。</p><span>当前：{board?.status==="success"?`成功 · ${fmt(board.fetchedAt)}`:board?.status==="failed"?"抓取失败":"等待采集"}</span></div></section><footer><span>CHANNEL BESTSELLER RADAR</span><span>DAILY SNAPSHOT · DUBAI 08:00</span></footer></main>}
function Filter({title,items,value,onChange}:{title:string;items:{id:string;label:string}[];value:string;onChange:(v:string)=>void}){return <div className="control-group"><small>{title}</small><div>{items.map(x=><button key={x.id} className={value===x.id?"active":""} onClick={()=>onChange(x.id)}>{x.label}</button>)}</div></div>}
function Failure({board,loading}:{board:Board|undefined;loading:boolean}){return <div className="scrape-failure"><span>!</span><div><small>{loading?"LOADING":"SCRAPE FAILED"}</small><h3>{loading?"正在读取采集结果":board?.status==="pending"?"等待首次自动采集":"该榜单本次抓取失败"}</h3><p>{board?.error||"每日任务将在迪拜时间 08:00 自动运行。"}</p><footer>上次成功：{fmt(board?.lastSuccessAt||null)}</footer></div></div>}
